In [1]:
# Q1. Get your basics right - Implement selection sort algorithm in python. The function accepts a
# list in the input and returns a sorted list.
# E.g.
# Input f1([5,416,54,21,6135,15,741]) should
# Return [5, 15, 21, 54, 416, 741, 6135]
# Selection sort in Python
# time complexity O(n*n)
#sorting by finding min_index


def selection_sort(arr):
    n = len(arr)
    for i in range(n-1):
        min_idx = i
        for j in range(i+1, n):
            if arr[j] < arr[min_idx]:
                min_idx = j
        arr[i], arr[min_idx] = arr[min_idx], arr[i]
    return arr


#E.g    
input_list = [5, 416, 54, 21, 6135, 15, 741]
sorted_list = selection_sort(input_list)
print(sorted_list)



[5, 15, 21, 54, 416, 741, 6135]


The function returns the sorted list' [5, 15, 21, 54, 416, 741, 6135]' using the selection sort algorithm.

In [2]:
# Q2. Dictionary, what?
# Write a program that returns the file type from a file name. The type of the file is determined
# from the extension. Initially, a list of values of the form "extension,type"(e.g. xls,spreadsheet;
# png,image) will be input.
# The program takes input in the following form:
# 1. Input extension and type values in the form of a string having the following format:
# a. "extension1,type1;extension2,type2;extension3,type3"
# b. E.g. If we needed to input xls → spreadsheet, xlsx → spreadsheet, jpg → image
# our string would be something like: "xls,spreadsheet;xlsx,spreadsheet;jpg,image"
# 2. Input a list of filename.extension. E.g. an input list could be something like ["abc.html",
# "xyz.xls", "text.csv", "123"]
# The program should return a dict of filename: type pairs
# E.g.
# f("xls,spreadsheet;xlsx,spreadsheet;jpg,image", ["abc.jpg",
# "xyz.xls", "text.csv", "123"]) should return
# {
# "abc.jpg": "image",
# "xyz.xls": "spreadsheet",
# "Text.csv": "unknown",
# "123": "unknown"
# }
#Ans ==>> Dictionary -> In Python, a dictionary is an unordered collection of key-value pairs, where each key is unique.
#Dictionaries are mutable in Python, which means they can be changed after they are created.
#E.g -> my_dict = {"name": "John", "age": 25, "city": "New York"}


def get_file_type(extension_type_list, filenames):
    extension_type_pairs = extension_type_list.split(';')
    extension_type_dict = {}
    for pair in extension_type_pairs:
        extension, file_type = pair.split(',')
        extension_type_dict[extension] = file_type

    file_type_dict = {}
    for filename in filenames:
        if '.' in filename:
            extension = filename.split('.')[-1]
            file_type = extension_type_dict.get(extension, 'unknown')
        else:
            file_type = 'unknown'
        file_type_dict[filename] = file_type

    return file_type_dict

#E.g
extension_type_list = "xls,spreadsheet;xlsx,spreadsheet;jpg,image"
filenames = ["abc.jpg", "xyz.xls", "text.csv", "123"]
result = get_file_type(extension_type_list, filenames)
print(result)


{'abc.jpg': 'image', 'xyz.xls': 'spreadsheet', 'text.csv': 'unknown', '123': 'unknown'}


In [3]:
 #3. Given a list of dicts, write a program to sort the list according to a key given in input.
#  E.g.
# Input f([
# {"fruit": "orange", "color": "orange"},
# {"fruit": "apple", "color": "red"},
# {"fruit": "banana", "color": "yellow"},
# {"fruit": "blueberry", "color": "blue"}
# ], "fruit")
# Should Output
# [
# {"fruit": "apple", "color": "red"},
# {"fruit": "banana", "color": "yellow"},
# {"fruit": "blueberry", "color": "blue"},
# {"fruit": "orange", "color": "orange"}
# ]
# AND
# Input f([
# {"fruit": "orange", "color": "orange"},
# {"fruit": "apple", "color": "red"},
# {"fruit": "banana", "color": "yellow"},
# {"fruit": "blueberry", "color": "blue"}
# ], "color")
# Should Output
# [
# {"fruit": "blueberry", "color": "blue"},
# {"fruit": "orange", "color": "orange"},
# {"fruit": "apple", "color": "red"},
# {"fruit": "banana", "color": "yellow"}
# ]


def sort_list_of_dicts(list_of_dicts, sort_key):
    sorted_list = sorted(list_of_dicts, key=lambda x: x[sort_key])
    return sorted_list


# E.g
list_of_dicts = [
    {"fruit": "orange", "color": "orange"},
    {"fruit": "apple", "color": "red"},
    {"fruit": "banana", "color": "yellow"},
    {"fruit": "blueberry", "color": "blue"}
]

sorted_list_by_fruit = sort_list_of_dicts(list_of_dicts, "fruit")
print(sorted_list_by_fruit)

sorted_list_by_color = sort_list_of_dicts(list_of_dicts, "color")
print(sorted_list_by_color)


[{'fruit': 'apple', 'color': 'red'}, {'fruit': 'banana', 'color': 'yellow'}, {'fruit': 'blueberry', 'color': 'blue'}, {'fruit': 'orange', 'color': 'orange'}]
[{'fruit': 'blueberry', 'color': 'blue'}, {'fruit': 'orange', 'color': 'orange'}, {'fruit': 'apple', 'color': 'red'}, {'fruit': 'banana', 'color': 'yellow'}]


In [4]:
# 4.The power of one line -
# Given a dictionary, switch position of key and values in the dict, i.e., value becomes the key and
# key becomes value. The function's body shouldn't have more than one statement.
# f({
# "key1": "value1",
# "key2": "value2",
# "key3": "value3",
# "key4": "value4",
# "key5": "value5"
# }) should return
# {
# "value1": "key1",
# "value2": "key2",
# "value3": "key3",
# "value4": "key4",
# "value5": "key5"
# }
#Solution ->


def switch_key_value_pairs(dict):
    return {value: key for key, value in dict.items()}

#E.g
result = switch_key_value_pairs({
    "key1": "value1",
    "key2": "value2",
    "key3": "value3",
    "key4": "value4",
    "key5": "value5"
})

print(result)


{'value1': 'key1', 'value2': 'key2', 'value3': 'key3', 'value4': 'key4', 'value5': 'key5'}


In [5]:
# Q5. Common, Not Common
# Given 2 lists in input. Write a program to return the elements, which are common to both
# lists(set intersection) and those which are not common(set symmetric difference) between the
# lists.
# Input:
# Mainstream = ["One Punch Man","Attack On Titan","One Piece","Sword
# Art Online","Bleach","Dragon Ball Z","One Piece"]
# must_watch = ["Full Metal Alchemist","Code Geass","Death
# Note","Stein's Gate","The Devil is a Part Timer!","One Piece","Attack
# On Titan"]
# f(mainstream, must_watch) should return:
# ["One Piece", "Attack On Titan"], ["Dragon Ball Z", "Death Note",
# "One Punch Man", "Stein's Gate", "The Devil is a Part Timer!", "Sword
# Art Online","Full Metal Alchemist","'Bleach", "Code Geass"]


def compare_lists(list1, list2):
    Common_elements = list(set(list1) & set(list2))
    Not_common_elements = list(set(list1) ^ set(list2))
    return Common_elements, Not_common_elements

    #E.g input

Mainstream = ["One Punch Man","Attack On Titan","One Piece","Sword Art Online","Bleach","Dragon Ball Z","One Piece"]
must_watch = ["Full Metal Alchemist","Code Geass","Death Note","Stein's Gate","The Devil is a Part Timer!","One Piece","Attack On Titan"]
Common_elements, Not_common_elements = compare_lists(Mainstream, must_watch)

#print elements
print("Common elements:", Common_elements)
print("Uncommon elements:", Not_common_elements)


Common elements: ['One Piece', 'Attack On Titan']
Uncommon elements: ['Death Note', "Stein's Gate", 'Code Geass', 'The Devil is a Part Timer!', 'Dragon Ball Z', 'Bleach', 'One Punch Man', 'Sword Art Online', 'Full Metal Alchemist']


In [6]:
# Q.6 Given a list and 2 indices as input, return the sub-list enclosed within these 2 indices. It should
# contain every second element.
# E.g.
# Input f([2,3,5,7,11,13,17,19,23,29,31,37,41], 2, 9)

def get_sublist(lst, start_index, end_index):
    return lst[start_index:end_index + 1:2]


#E.g
result = get_sublist([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41], 2, 9)
print(result)


[5, 11, 17, 23]


In [7]:
#Q7. Calculate the factorial of a number using lambda function.

factorial = lambda n: 1 if n == 0 else n * factorial(n - 1)

number = 5
result = factorial(number)
print(f"The factorial of {number} is: {result}")


The factorial of 5 is: 120


In [8]:
# Q8. Some neat tricks up her sleeve:
# Looking at the below code, write down the final values of A0, A1, ...An
# A0 = dict(zip(('a','b','c','d','e'),(1,2,3,4,5)))
# A1 = range(10)
# A2 = sorted([i for i in A1 if i in A0])
# A3 = sorted([A0[s] for s in A0])
# A4 = [i for i in A1 if i in A3]
# A5 = {i:i*i for i in A1}
# A6 = [[i,i*i] for i in A1]
# A7 = reduce(lambda x,y: x+y, [10,23, -45, 33])
# A8 = map(lambda x: x*2, [1,2,3,4])
# A9 = filter(lambda x: len(x) >3, [“I” , “want”, “to”, “learn”, “python”])


from functools import reduce

A0 = dict(zip(('a', 'b', 'c', 'd', 'e'), (1, 2, 3, 4, 5)))
A1 = range(10)
A2 = sorted([i for i in A1 if i in A0])
A3 = sorted([A0[s] for s in A0])
A4 = [i for i in A1 if i in A3]
A5 = {i: i*i for i in A1}
A6 = [[i, i*i] for i in A1]
A7 = reduce(lambda x, y: x + y, [10, 23, -45, 33])
A8 = list(map(lambda x: x*2, [1, 2, 3, 4]))
A9 = list(filter(lambda x: len(x) > 3, ["I", "want", "to", "learn", "python"]))

print(A0)
print(list(A1))
print(A2)
print(A3)
print(A4)
print(A5)
print(A6)
print(A7)
print(A8)
print(A9)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}
[[0, 0], [1, 1], [2, 4], [3, 9], [4, 16], [5, 25], [6, 36], [7, 49], [8, 64], [9, 81]]
21
[2, 4, 6, 8]
['want', 'learn', 'python']


In [9]:
# Q9.
# Write a func that takes 3 args:
# from_date - string representing a date in the form of 'yy-mm-dd'
# to_date - string representing a date in the form of 'yy-mm-dd'
# difference - int
# Returns True if from_date and to_date are less than difference days away from each other, else
# returns False.

from datetime import datetime, timedelta

def check_date_difference(from_date, to_date, difference):
    date_format = "%y-%m-%d"
    date1 = datetime.strptime(from_date, date_format)
    date2 = datetime.strptime(to_date, date_format)
    days_difference = (date2 - date1).days
    return days_difference < difference
  

result1 = check_date_difference('21-05-01', '21-05-10', 10)
print(result1)  # Output: True

result2 = check_date_difference('21-05-01', '21-05-10', 9)
print(result2)  # Output: False


True
False


In [10]:
# Q10. Of date and days
# Write a func that takes 2 args:
# date - string representing a date in the form of 'yy-mm-dd'
# n - integer
# Returns the string representation of date n days before 'date'
# E.g. f('16-12-10', 11) should return '16-11-29'

from datetime import datetime, timedelta

def get_previous_date(date, n):
    date_format = "%y-%m-%d"
    given_date = datetime.strptime(date, date_format)
    previous_date = given_date - timedelta(days=n)
    return previous_date.strftime(date_format)
    
#E.g

result = get_previous_date('16-12-10', 11)
print(result)  # Output: 16-11-29


16-11-29


In [11]:
# Q11. Something fishy there -
# Find output of following:
# def f(x,l=[]):
# for i in range(x):
# l.append(i*i)
# print(l)
# f(2)
# f(3,[3,2,1])
# f(3)

def f(x, l=[]):
    for i in range(x):
        l.append(i * i)
    print(l)

#E.g

f(2)
f(3,[3,2,1])
f(3)


[0, 1]
[3, 2, 1, 0, 1, 4]
[0, 1, 0, 1, 4]
